# Generated by Django 4.1.1 on 2022-11-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
