# Generated by Django 4.1.1 on 2022-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0003_rename_name_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='In-Active', max_length=30),
        ),
    ]
