# Generated by Django 4.1.1 on 2022-12-02 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0004_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_brandname', models.CharField(max_length=500)),
                ('Product_discription', models.CharField(max_length=500)),
                ('Product_price', models.FloatField()),
                ('Product_image', models.ImageField(default='default.jpg', upload_to='products/')),
                ('Product_qty', models.IntegerField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OP_app.product_category')),
            ],
        ),
    ]
