# Generated by Django 4.1.1 on 2022-12-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0005_product_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_discription',
            field=models.TextField(max_length=500),
        ),
    ]
