# Generated by Django 4.1.1 on 2022-12-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0006_alter_product_product_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='cat_img',
            field=models.ImageField(default='default.jpg', upload_to='category/'),
        ),
    ]
