# Generated by Django 4.1.1 on 2022-12-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0007_product_category_cat_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField(max_length=10)),
                ('total_price', models.IntegerField(max_length=6)),
                ('dateTime', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OP_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OP_app.user')),
            ],
        ),
    ]
