# Generated by Django 4.1.1 on 2022-12-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
