# Generated by Django 4.1.1 on 2023-01-01 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0010_alter_cart_product_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OP_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OP_app.user')),
            ],
        ),
    ]
