# Generated by Django 4.1.1 on 2023-01-21 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0012_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_qty', models.IntegerField(max_length=10)),
                ('Sub_total_price', models.FloatField(max_length=10)),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OP_app.order')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OP_app.product')),
            ],
        ),
    ]
