# Generated by Django 4.1.1 on 2023-01-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0014_billing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='Order_id',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='Product_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_item',
        ),
    ]
