# Generated by Django 4.1.1 on 2023-01-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0015_delete_billing_remove_order_item_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=15)),
                ('Last_name', models.CharField(max_length=15)),
                ('Adress', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=200)),
                ('Zip', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('mobile_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OP_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_qty', models.IntegerField()),
                ('Sub_total_price', models.FloatField(max_length=10)),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OP_app.order')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OP_app.product')),
            ],
        ),
    ]
