# Generated by Django 4.1.1 on 2023-01-26 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0016_billing_order_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='mobile_no',
            new_name='Mobile_no',
        ),
    ]
