# Generated by Django 4.1.1 on 2023-01-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0017_rename_mobile_no_billing_mobile_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='Order_id',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='Product_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_item',
        ),
    ]
