# Generated by Django 4.1.1 on 2023-02-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0019_order_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
