# Generated by Django 4.1.1 on 2023-02-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0020_user_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
