# Generated by Django 4.1.1 on 2023-02-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OP_app', '0021_rename_adress_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='unpaid', max_length=100, null=True),
        ),
    ]
